### ISSUE TITLE
效果不错，数据量大的时候会卡顿，需要优化

### ISSUE THREAD

**Issue by Ystarz** [QQ648380421/UnityTableExcel#1]
300多行，20列的数据量，帧数就很低了，后续可能需要优化
![微信图片_20221224114258](https://user-images.githubusercontent.com/14012723/209420077-5cadb5e8-3d65-4e78-bde3-2b5833aeb290.png)

**Comment by QQ648380421** [comment]
优化中

**Comment by QQ648380421** [comment]
![QQ截图20221230185412](https://user-images.githubusercontent.com/40554493/210064241-52f87ccb-b049-4c7a-a73e-2aa53fd9ecae.png)
测试过50*530个单元格数据，能稳定在300帧左右了
